/**
 * ═══════════════════════════════════════════════════════════════════
 *  GESTIONE OPERE — GUIDA DEFINITIVA
 * ═══════════════════════════════════════════════════════════════════
 *
 *  ── CONVENZIONE NOMI FILE (regola unica e rigorosa) ──────────
 *  Ogni file dell'opera DEVE seguire questo schema:
 *
 *    massimo-di-stefano-{slug}-{category}-{tipo}.{format}
 *
 *  Tipi:
 *    • preview            → thumbnail per la galleria
 *    • 1                  → immagine principale (main / full)
 *    • detail-1, detail-2 → dettagli ravvicinati
 *    • room-view-1, ...   → opera ambientata
 *
 *  Esempio:
 *    massimo-di-stefano-pensieri-in-evoluzione-painting-preview.jpg
 *    massimo-di-stefano-pensieri-in-evoluzione-painting-1.jpg
 *    massimo-di-stefano-pensieri-in-evoluzione-painting-detail-1.jpg
 *    massimo-di-stefano-pensieri-in-evoluzione-painting-room-view-1.jpg
 *
 *  ── COME AGGIUNGERE UN'OPERA ──────────────────────────────────
 *  1. Crea la cartella:  public/artworks/{categoria}/{slug}/
 *     Esempio:           public/artworks/painting/nebulosa-urbana/
 *
 *  2. Carica i file rispettando la convenzione qui sopra.
 *     Formato: .jpg (default) o .webp (specifica `format: "webp"`).
 *
 *  3. Aggiungi un blocco createArtwork({...}) nell'array della categoria.
 *
 *  ── TEMPLATE DA COPIARE ─────────────────────────────────────
 *
 *     createArtwork({
 *       slug: "titolo-in-minuscolo",   // identifica cartella, file e URL
 *       category: "painting",          // painting | photography | digital-art | t-shirt
 *       title: "Titolo Opera",
 *       year: "2024",
 *       dimensions: "100 × 50 cm",
 *       technique: "Tecnica mista su tela",
 *       price: "€ 1.500",              // opzionale
 *       details: 3,                     // numero di foto detail (0 se nessuna)
 *       roomViews: 2,                   // numero di foto room-view (0 se nessuna)
 *       format: "jpg",                  // opzionale: "jpg" (default) | "webp"
 *     }),
 *
 *  ── REGOLE ──────────────────────────────────────────────────
 *  • L'ID dell'opera coincide SEMPRE con lo slug (URL SEO-friendly).
 *  • Lo slug deve corrispondere al nome della cartella e dei file.
 *  • La categoria appare SEMPRE nel nome di OGNI file.
 *  • Categorie valide: painting, photography, digital-art, t-shirt.
 *  • Le opere senza file reali appaiono come placeholder colorati
 *    (gradiente generato dallo slug) — vedi src/lib/slugGradient.ts.
 *  • Per l'Archive usa il file separato: src/lib/archiveData.ts.
 *
 * ═══════════════════════════════════════════════════════════════════
 */

export interface ArtworkFullData {
  id: string;
  title: string;
  year: string;
  dimensions: string;
  technique: string;
  price?: string;
  preview: string;
  main: string;
  full: string;
  images: { url: string; label: string }[];
  /** True quando i file fisici esistono — entra in sitemap.xml */
  published: boolean;
}

/* ─── Helper: genera automaticamente i percorsi immagine ─── */

interface CreateArtworkInput {
  slug: string;
  category: string;
  title: string;
  year: string;
  dimensions: string;
  technique: string;
  price?: string;
  details?: number;
  roomViews?: number;
  format?: "jpg" | "webp";
  /** Imposta a true SOLO se i file immagine esistono fisicamente. Default: false. */
  published?: boolean;
}

function createArtwork(input: CreateArtworkInput): ArtworkFullData {
  const {
    slug,
    category,
    title,
    year,
    dimensions,
    technique,
    price,
    details = 0,
    roomViews = 0,
    format = "jpg",
    published = false,
  } = input;

  const dir = `/artworks/${category}/${slug}`;
  // Prefisso unico: include SEMPRE la categoria. Vale per ogni tipo di file.
  const base = `${dir}/massimo-di-stefano-${slug}-${category}`;
  const ext = format;

  const images: { url: string; label: string }[] = [];

  for (let i = 1; i <= roomViews; i++) {
    images.push({ url: `${base}-room-view-${i}.${ext}`, label: `Room View ${i}` });
  }
  for (let i = 1; i <= details; i++) {
    images.push({ url: `${base}-detail-${i}.${ext}`, label: `Dettaglio ${i}` });
  }

  return {
    id: slug, // ID === slug (URL SEO-friendly)
    title,
    year,
    dimensions,
    technique,
    price,
    preview: `${base}-preview.${ext}`,
    main: `${base}-1.${ext}`,
    full: `${base}-1.${ext}`,
    images,
    published,
  };
}

type DisciplineData = Record<string, ArtworkFullData[]>;

/* ═══════════════════════════════════════════════════════════════
 *  PAINTING
 * ═══════════════════════════════════════════════════════════════ */
const painting: ArtworkFullData[] = [
createArtwork({
  slug: "exotic-trip",
  category: "painting",
  title: "Exotic trip",
  year: "2014",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 400",
  details: 8,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "ancient-traces",
  category: "painting",
  title: "Ancient traces",
  year: "2012",
  dimensions: "60 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 250",
  details: 5,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "acid-dream",
  category: "painting",
  title: "Acid dream",
  year: "2019",
  dimensions: "50 x 39 x 2 cm",
  technique: "mista su tela",
  price: "€ 190",
  details: 5,
  roomViews: 4,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "12-12-2012",
  category: "painting",
  title: "12 - 12 - 2012",
  year: "2012",
  dimensions: "52 x 56 x 2 cm",
  technique: "Mista su tavola",
  price: "€ 500",
  details: 5,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "bassa-marea",
  category: "painting",
  title: "Bassa marea",
  year: "2012",
  dimensions: "120 x 62 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 800",
  details: 5,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "pensieri-in-evoluzione",
  category: "painting",
  title: "Pensieri in evoluzione",
  year: "2014",
  dimensions: "60 x 120 x 2 cm",
  technique: "Mixed on polistyrene board",
  price: "€ 500",
  details: 3,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "searching-for-you",
  category: "painting",
  title: "Searching for you",
  year: "2012",
  dimensions: "80 x 120 x 2 cm",
  technique: "Mixed on canvas",
  price: "€ 800",
  details: 4,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "locchio-della-mente",
  category: "painting",
  title: "L'occhio della mente",
  year: "2010",
  dimensions: "53 x 53 x 2 cm",
  technique: "Mista su legno",
  price: "€ 300",
  details: 4,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "il-settimo-chakra",
  category: "painting",
  title: "Il settimo Chakra",
  year: "2019",
  dimensions: "60 x 60 x 4 cm",
  technique: "Mista su polistirene",
  price: "€ 250",
  details: 4,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "abissi-mentali",
  category: "painting",
  title: "Abissi mentali",
  year: "2010",
  dimensions: "53 x 53 x 2 cm",
  technique: "Mista su legno",
  price: "€ 250",
  details: 2,
  roomViews: 5,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "mutamento",
  category: "painting",
  title: "Mutamento",
  year: "2011",
  dimensions: "120 x 60 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 400",
  details: 7,
  roomViews: 6,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "embrione-alieno",
  category: "painting",
  title: "Embrione alieno",
  year: "2010",
  dimensions: "80 x 70 x 2 cm",
  technique: "mista su legno",
  price: "€ 700",
  details: 6,
  roomViews: 4,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "catarsi",
  category: "painting",
  title: "Catarsi",
  year: "2014",
  dimensions: "60 x 120 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 800",
  details: 6,
  roomViews: 4,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "connection-for-ever",
  category: "painting",
  title: "Connection for ever",
  year: "2017",
  dimensions: "80 x 100 x 1 cm",
  technique: "Mista su tela",
  price: "€ 600",
  details: 7,
  roomViews: 6,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "orbs",
  category: "painting",
  title: "Orbs",
  year: "2011",
  dimensions: "80 x 80 x 2 cm",
  technique: "Mista su tela",
  price: "€ 600",
  details: 7,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "neuronic-dance",
  category: "painting",
  title: "Neuronic dance",
  year: "2022",
  dimensions: "79 x 59 x 1 cm",
  technique: "Mista su polistirene",
  price: "€ 250",
  details: 4,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "emersione",
  category: "painting",
  title: "Emersione",
  year: "2023",
  dimensions: "120 x 60 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 400",
  details: 7,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "il-consolatore",
  category: "painting",
  title: "Il Consolatore",
  year: "2019",
  dimensions: "39 x 29 x 3 cm",
  technique: "Mista su cartoncino",
  price: "€ 60",
  details: 7,
  roomViews: 4,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "immersione-nel-nulla",
  category: "painting",
  title: "Immersione nel nulla",
  year: "2020",
  dimensions: "60 x 60 x 2 cm",
  technique: "mista su polistirene",
  price: "€ 250",
  details: 5,
  roomViews: 5,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "serie-energia-energia-rossa",
  category: "painting",
  title: "Serie Energia - Energia rossa",
  year: "2019",
  dimensions: "39 x 29 x 2 cm",
  technique: "Acrilico",
  price: "€ 45",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "estasi",
  category: "painting",
  title: "Estasi",
  year: "2010",
  dimensions: "56 x 72 x 2 cm",
  technique: "mista su legno",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "something-is-happening",
  category: "painting",
  title: "Something is happening",
  year: "2013",
  dimensions: "60 x 120 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 650",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "lindiano",
  category: "painting",
  title: "L'indiano",
  year: "2009",
  dimensions: "62 x 62 cm",
  technique: "Mista su faesite",
  price: "€ 260",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "trappola-ingannevole",
  category: "painting",
  title: "Trappola ingannevole",
  year: "2013",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "lacerazione-sublime",
  category: "painting",
  title: "Lacerazione sublime",
  year: "2013",
  dimensions: "60 x 60 x 1 cm",
  technique: "Mista e gesso su tavola",
  price: "€ 250",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "inside-the-heart",
  category: "painting",
  title: "Inside the heart",
  year: "2012",
  dimensions: "120 x 62 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "blossom-time",
  category: "painting",
  title: "Blossom time",
  year: "2017",
  dimensions: "45 x 30 x 2 cm",
  technique: "mista su legno",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "duplice-sguardo",
  category: "painting",
  title: "Duplice sguardo",
  year: "2020",
  dimensions: "120 x 60 x 3 cm",
  technique: "mista su polistirene",
  price: "€ 1000",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "stato-confusionale",
  category: "painting",
  title: "Stato confusionale",
  year: "2021",
  dimensions: "39 x 29 x 2 cm",
  technique: "mista su carta e plastica",
  price: "€ 100",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "coscienza",
  category: "painting",
  title: "Coscienza",
  year: "2010",
  dimensions: "100 x 100 x 4 cm",
  technique: "Mista su tela",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "ghosts",
  category: "painting",
  title: "Ghosts",
  year: "2010",
  dimensions: "60 x 67 x 1 cm",
  technique: "mista su legno",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "emozione-autunnale",
  category: "painting",
  title: "Emozione autunnale",
  year: "2022",
  dimensions: "30 x 40 x 1 cm",
  technique: "mista su tela",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "nucleo-energetico",
  category: "painting",
  title: "Nucleo energetico",
  year: "2020",
  dimensions: "34 x 34 x 4 cm",
  technique: "mista su polistirene",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "golden-dream",
  category: "painting",
  title: "Golden Dream",
  year: "2012",
  dimensions: "96 x 60 x 5 cm",
  technique: "Mista su legno",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "respiro-profondo",
  category: "painting",
  title: "Respiro profondo",
  year: "2014",
  dimensions: "80 x 100 x 2 cm",
  technique: "Acrilico",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "uscendo-dalle-tenebre",
  category: "painting",
  title: "Uscendo dalle tenebre",
  year: "2010",
  dimensions: "82 x 62 x 2 cm",
  technique: "Mista su tela",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "sleep-before-death",
  category: "painting",
  title: "Sleep before death",
  year: "2013",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "evoluzione",
  category: "painting",
  title: "Evoluzione",
  year: "2010",
  dimensions: "80 x 28 x 2 cm",
  technique: "Mista su legno",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "genesi",
  category: "painting",
  title: "Genesi",
  year: "2010",
  dimensions: "64 x 54 x 2 cm",
  technique: "Mista su legno",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "una-nuova-alba",
  category: "painting",
  title: "Una nuova alba",
  year: "2021",
  dimensions: "39 x 29 x 3 cm",
  technique: "Mista su cartoncino",
  price: "€ 60",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "rotten-brain",
  category: "painting",
  title: "Rotten brain",
  year: "2020",
  dimensions: "60 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 90",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "dentro-i-confini",
  category: "painting",
  title: "Dentro i confini",
  year: "2019",
  dimensions: "29 x 39 x 3 cm",
  technique: "mista su cartoncino",
  price: "€ 60",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "esperienza",
  category: "painting",
  title: "Esperienza",
  year: "2016",
  dimensions: "70 x 100 x 2 cm",
  technique: "Tecnica mista",
  price: "€ 350",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "notte-di-attesa",
  category: "painting",
  title: "Notte di attesa",
  year: "2010",
  dimensions: "150 x 100 x 4 cm",
  technique: "Mista su tela",
  price: "€ 1500",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "evolvenza-1",
  category: "painting",
  title: "Evolvenza 1",
  year: "2022",
  dimensions: "20 x 20 x 1 cm",
  technique: "Mista su tela",
  price: "€ 100",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "connessioni-neuronali",
  category: "painting",
  title: "Connessioni neuronali",
  year: "2010",
  dimensions: "80 x 120 x 4 cm",
  technique: "Mista 3D su tela",
  price: "€ 900",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "cosmic-vortix",
  category: "painting",
  title: "Cosmic vortix",
  year: "2010",
  dimensions: "104 x 72 x 1 cm",
  technique: "Mista su legno",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "turn-off-your-mind",
  category: "painting",
  title: "Turn off your mind",
  year: "2013",
  dimensions: "120 x 60 x 3 cm",
  technique: "mista su polistirene",
  price: "€ 350",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "silver-energy",
  category: "painting",
  title: "Silver Energy",
  year: "2010",
  dimensions: "120 x 60 x 2 cm",
  technique: "mista su legno",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "bianco",
  category: "painting",
  title: "Bianco",
  year: "2011",
  dimensions: "28 x 60 x 2 cm",
  technique: "Mista su legno",
  price: "€ 500",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "dentro-il-tempo",
  category: "painting",
  title: "Dentro il tempo",
  year: "2011",
  dimensions: "77 x 53 x 4 cm",
  technique: "Mista su tavola",
  price: "€ 800",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "serie-riflessioni-5-dic-2019",
  category: "painting",
  title: "Serie riflessioni 5 dic 2019",
  year: "2019",
  dimensions: "39 x 29 x 2 cm",
  technique: "Mista su cartoncino",
  price: "€ 60",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "searching-for-balance-4-am",
  category: "painting",
  title: "Searching for balance 4 AM",
  year: "2011",
  dimensions: "80 x 80 x 1 cm",
  technique: "Mista su tela",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "unforgettable-dream",
  category: "painting",
  title: "Unforgettable dream",
  year: "2014",
  dimensions: "60 x 120 x 3 cm",
  technique: "mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "milky-way",
  category: "painting",
  title: "Milky way",
  year: "2013",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "frammenti",
  category: "painting",
  title: "Frammenti",
  year: "2010",
  dimensions: "80 x 35 x 2 cm",
  technique: "Mista a rilievo su tavola",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "what-remains-is-only-a-flower",
  category: "painting",
  title: "What remains is only a flower",
  year: "2021",
  dimensions: "44 x 32 x 2 cm",
  technique: "mista su forex",
  price: "€ 150",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "inside-me",
  category: "painting",
  title: "Inside me",
  year: "2010",
  dimensions: "120 x 80 x 2 cm",
  technique: "Mista su tela",
  price: "€ 1000",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "i-sentimenti-fuggono-il-pensiero",
  category: "painting",
  title: "I sentimenti fuggono il pensiero",
  year: "2017",
  dimensions: "60 x 120 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "la-lama-del-desiderio",
  category: "painting",
  title: "La lama del desiderio",
  year: "2022",
  dimensions: "95 x 37 cm",
  technique: "mista su tavola",
  price: "€ 250",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "ricordi-che-bruciano",
  category: "painting",
  title: "Ricordi che bruciano",
  year: "2021",
  dimensions: "29 x 39 cm",
  technique: "Mista su cartoncino",
  price: "€ 80",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "initium-vitae",
  category: "painting",
  title: "Initium vitae",
  year: "2013",
  dimensions: "120 x 70 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 500",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "etereo",
  category: "painting",
  title: "Etereo",
  year: "2018",
  dimensions: "24 x 30 x 2 cm",
  technique: "Mista su tela",
  price: "€ 150",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "amore-e-tormento",
  category: "painting",
  title: "Amore e tormento",
  year: "2017",
  dimensions: "34 x 34 x 4 cm",
  technique: "Mista 3D su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "your-mask-is-mine",
  category: "painting",
  title: "Your mask is mine",
  year: "2019",
  dimensions: "30 x 40 x 3 cm",
  technique: "mista su tela",
  price: "€ 200",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "balance",
  category: "painting",
  title: "Balance",
  year: "2010",
  dimensions: "90 x 90 x 2 cm",
  technique: "Mista su tela",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "tumulto-energetico",
  category: "painting",
  title: "Tumulto energetico",
  year: "2020",
  dimensions: "80 x 124 x 3 cm",
  technique: "mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "when-memories-make-you-sick",
  category: "painting",
  title: "When memories make you sick",
  year: "2013",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 900",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "devils",
  category: "painting",
  title: "Devils",
  year: "2010",
  dimensions: "100 x 70 x 2 cm",
  technique: "mista su tela",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "energia-rossa",
  category: "painting",
  title: "Energia rossa",
  year: "2021",
  dimensions: "54 x 36 x 1 cm",
  technique: "mista su tavola",
  price: "€ 200",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "tracce-di-unanima",
  category: "painting",
  title: "Tracce di un'anima",
  year: "2017",
  dimensions: "80 x 19 x 1 cm",
  technique: "Mista in rilievo su tavola",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "the-night-of-summer-solstice",
  category: "painting",
  title: "The night of Summer solstice",
  year: "2019",
  dimensions: "29 x 39 x 3 cm",
  technique: "Mista su tela",
  price: "€ 150",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "spazio-lunare",
  category: "painting",
  title: "Spazio lunare",
  year: "2009",
  dimensions: "84 x 60 x 2 cm",
  technique: "mista su tavola",
  price: "€ 1000",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "embrione",
  category: "painting",
  title: "Embrione",
  year: "2010",
  dimensions: "80 x 60 x 4 cm",
  technique: "Mista su tela",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "metropolis",
  category: "painting",
  title: "Metropolis",
  year: "2009",
  dimensions: "50 x 70 x 2 cm",
  technique: "Mista su tela",
  price: "€ 300",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "oltre-il-confine-della-vita",
  category: "painting",
  title: "Oltre il confine della vita",
  year: "2018",
  dimensions: "34 x 34 x 4 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "principium",
  category: "painting",
  title: "Principium",
  year: "2019",
  dimensions: "39 x 29 x 3 cm",
  technique: "Mista su cartoncino",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "in-the-depths-of-the-soul",
  category: "painting",
  title: "In the depths of the soul",
  year: "2012",
  dimensions: "60 x 120 x 3 cm",
  technique: "mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "la-collina-delle-rivelazioni",
  category: "painting",
  title: "La collina delle rivelazioni",
  year: "2021",
  dimensions: "49 x 40 x 2 cm",
  technique: "Mista su espanso",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "il-risveglio-dopo-la-stasi",
  category: "painting",
  title: "Il risveglio dopo la stasi",
  year: "2017",
  dimensions: "34 x 34 x 4 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "energia-in-movimento",
  category: "painting",
  title: "Energia in movimento",
  year: "2020",
  dimensions: "80 x 60 x 2 cm",
  technique: "Mista su tela",
  price: "€ 140",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "lo-sgretolamento-dellego",
  category: "painting",
  title: "Lo sgretolamento dell'ego",
  year: "2019",
  dimensions: "120 x 60 x 3 cm",
  technique: "mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "emozione-invernale",
  category: "painting",
  title: "Emozione invernale",
  year: "2020",
  dimensions: "120 x 60 x 4 cm",
  technique: "mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "sentimenti-autunnali",
  category: "painting",
  title: "Sentimenti autunnali",
  year: "2022",
  dimensions: "60 x 120 x 2 cm",
  technique: "mista su polistirene",
  price: "€ 500",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "confusion-is-order",
  category: "painting",
  title: "Confusion is order",
  year: "2013",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 250",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "the-storm",
  category: "painting",
  title: "The Storm",
  year: "2010",
  dimensions: "150 x 100 x 4 cm",
  technique: "Mista su tela",
  price: "€ 1200",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "everything-can-change",
  category: "painting",
  title: "Everything can change",
  year: "2014",
  dimensions: "60 x 120 x 2 cm",
  technique: "mista su polistirene",
  price: "€ 900",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "serie-energie-in-movimento",
  category: "painting",
  title: "Serie Energie in movimento",
  year: "2021",
  dimensions: "39 x 29 cm",
  technique: "Acrilico",
  price: "€ 80",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "lacqua-e-il-fuoco",
  category: "painting",
  title: "L'acqua e il fuoco",
  year: "2021",
  dimensions: "40 x 40 x 1 cm",
  technique: "Mista su tela",
  price: "€ 100",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "fluid-mind",
  category: "painting",
  title: "Fluid Mind",
  year: "2012",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 1000",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "astral-connection",
  category: "painting",
  title: "Astral connection",
  year: "2019",
  dimensions: "50 x 70 x 3 cm",
  technique: "Acrilico",
  price: "€ 160",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "anima-ferita",
  category: "painting",
  title: "Anima ferita",
  year: "2014",
  dimensions: "120 x 60 x 4 cm",
  technique: "mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "blessing-time",
  category: "painting",
  title: "Blessing time",
  year: "2020",
  dimensions: "34 x 34 x 4 cm",
  technique: "mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "serie-impronte-anima-10-dic",
  category: "painting",
  title: "Serie Impronte - Anima 10 Dic",
  year: "2019",
  dimensions: "42 x 42 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 130",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "confusional-state",
  category: "painting",
  title: "Confusional state",
  year: "2020",
  dimensions: "60 x 120 x 2 cm",
  technique: "mista su polistirene",
  price: "€ 250",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "before-the-creation",
  category: "painting",
  title: "Before the creation",
  year: "2013",
  dimensions: "120 x 60 x 4 cm",
  technique: "mista su polistirene",
  price: "€ 500",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "invisible-energy",
  category: "painting",
  title: "Invisible energy",
  year: "2010",
  dimensions: "38 x 94 x 5 cm",
  technique: "mista su legno",
  price: "€ 350",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "funny-soul",
  category: "painting",
  title: "Funny soul",
  year: "2021",
  dimensions: "50 x 60 x 2 cm",
  technique: "Mista su tela",
  price: "€ 150",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "disgelo",
  category: "painting",
  title: "Disgelo",
  year: "2021",
  dimensions: "39 x 29 x 3 cm",
  technique: "Acrilico",
  price: "€ 60",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "energie-danzanti",
  category: "painting",
  title: "Energie danzanti",
  year: "2023",
  dimensions: "29 x 39 cm",
  technique: "Mista su cartoncino",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "sotto-la-pelle",
  category: "painting",
  title: "Sotto la pelle",
  year: "2019",
  dimensions: "62 x 52 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 150",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "limbic-world",
  category: "painting",
  title: "Limbic world",
  year: "2019",
  dimensions: "39 x 29 x 3 cm",
  technique: "Mista su cartoncino",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "estremo",
  category: "painting",
  title: "Estremo",
  year: "2011",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 1000",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "fecondazione-cosmica",
  category: "painting",
  title: "Fecondazione cosmica",
  year: "2021",
  dimensions: "70 x 50 cm",
  technique: "Mista su polipropilene",
  price: "€ 120",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "geolica",
  category: "painting",
  title: "Geolica",
  year: "2012",
  dimensions: "120 x 60 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "il-dramma-dellamore",
  category: "painting",
  title: "Il dramma dell'amore",
  year: "2019",
  dimensions: "34 x 34 x 4 cm",
  technique: "Mista su polistirene",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "plasma-flux",
  category: "painting",
  title: "Plasma Flux",
  year: "2012",
  dimensions: "120 x 60 x 4 cm",
  technique: "mista su polistirene",
  price: "€ 500",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "emersione-2",
  category: "painting",
  title: "Emersione (2)",
  year: "2019",
  dimensions: "49 x 39 x 2 cm",
  technique: "Mista su polistirene",
  price: "€ 120",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "il-tormento-del-vivere",
  category: "painting",
  title: "Il tormento del vivere",
  year: "2023",
  dimensions: "29 x 39 x 1 cm",
  technique: "Mista su cartoncino",
  price: "€ 100",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "riflessione-fluida-18-12-2019",
  category: "painting",
  title: "Riflessione fluida 18-12-2019",
  year: "2019",
  dimensions: "39 x 29 x 1 cm",
  technique: "Acrilico",
  price: "€ 60",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "serie-impronte-foglia-rossa",
  category: "painting",
  title: "Serie impronte - Foglia rossa",
  year: "2021",
  dimensions: "85 x 40 x 2 cm",
  technique: "Mista su lana di vetro",
  price: "€ 250",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "affioramenti",
  category: "painting",
  title: "Affioramenti",
  year: "2020",
  dimensions: "44 x 32 x 2 cm",
  technique: "mista su forex",
  price: "€ 70",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "energia-buona",
  category: "painting",
  title: "Energia buona",
  year: "2021",
  dimensions: "30 x 30 x 3 cm",
  technique: "Mista su polistirene",
  price: "€ 60",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "before-the-astral-trip",
  category: "painting",
  title: "Before the astral trip",
  year: "2012",
  dimensions: "120 x 120 x 4 cm",
  technique: "Acrilico",
  price: "€ 600",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "rain",
  category: "painting",
  title: "Rain",
  year: "2010",
  dimensions: "80 x 80 x 4 cm",
  technique: "Mista su tela",
  price: "€ 350",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "falling-down",
  category: "painting",
  title: "Falling down",
  year: "2012",
  dimensions: "120 x 60 x 3 cm",
  technique: "mista su polistirene",
  price: "€ 400",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "sharp-blades",
  category: "painting",
  title: "Sharp blades",
  year: "2019",
  dimensions: "29 x 39 x 2 cm",
  technique: "Mista su cartoncino",
  price: "€ Collezione privata",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
];

/* ═══════════════════════════════════════════════════════════════
 *  PHOTOGRAPHY
 * ═══════════════════════════════════════════════════════════════ */
const photography: ArtworkFullData[] = [
createArtwork({
  slug: "and-the-rest-is-only-love",
  category: "photography",
  title: "And the rest is only love",
  year: "2016",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "the-new-world",
  category: "photography",
  title: "The new world",
  year: "2016",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "dalla-soffitta-in-giu",
  category: "photography",
  title: "Dalla soffitta in giù",
  year: "2016",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "drive-2",
  category: "photography",
  title: "Drive 2",
  year: "2015",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "i-am-the-life",
  category: "photography",
  title: "I am the life",
  year: "2016",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "assisi",
  category: "photography",
  title: "Assisi",
  year: "2016",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "una-vita-a-meta",
  category: "photography",
  title: "Una vita a metà",
  year: "2016",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "sogno-infranto",
  category: "photography",
  title: "Sogno infranto",
  year: "2015",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "stato-di-beatitudine-terrestre",
  category: "photography",
  title: "Stato di beatitudine terrestre",
  year: "2013",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "senza-tempo",
  category: "photography",
  title: "Senza tempo",
  year: "2015",
  dimensions: " x  cm",
  technique: "Fotografia Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 3,
  format: "webp",
  published: true,
}),
];

/* ═══════════════════════════════════════════════════════════════
 *  DIGITAL ART
 * ═══════════════════════════════════════════════════════════════ */
const digitalArt: ArtworkFullData[] = [
createArtwork({
  slug: "anima-indomabile",
  category: "digital-art",
  title: "Anima indomabile",
  year: "2019",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "the-worst-side-of-me",
  category: "digital-art",
  title: "The worst side of me",
  year: "2018",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "we-are-the-master",
  category: "digital-art",
  title: "We are the Master",
  year: "2018",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 1,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "espansione-cosmica",
  category: "digital-art",
  title: "Espansione Cosmica",
  year: "2020",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 3,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "the-new-dream",
  category: "digital-art",
  title: "The new dream",
  year: "2014",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 2,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "old-life",
  category: "digital-art",
  title: "Old life",
  year: "2017",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 0,
  format: "webp",
  published: false,
}),
createArtwork({
  slug: "tomorrow-morning",
  category: "digital-art",
  title: "Tomorrow morning",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "forgotten-hopes",
  category: "digital-art",
  title: "Forgotten hopes",
  year: "2020",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 1,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "plasmadonius",
  category: "digital-art",
  title: "Plasmadonius",
  year: "2021",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "abissi",
  category: "digital-art",
  title: "Abissi",
  year: "2023",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 1,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "in-memory-of-david-bowie-10-01-2016",
  category: "digital-art",
  title: "In memory of David Bowie 10-01-2016",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 2,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "la-visione-delle-4-am",
  category: "digital-art",
  title: "La visione delle 4 AM",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "the-last-vision",
  category: "digital-art",
  title: "The Last Vision",
  year: "2014",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 3,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "captured-soul-2",
  category: "digital-art",
  title: "Captured soul 2",
  year: "2023",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 1,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "close-to-the-soul",
  category: "digital-art",
  title: "Close to the soul",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "neuronal-expansion",
  category: "digital-art",
  title: "Neuronal expansion",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "flowers",
  category: "digital-art",
  title: "Flowers",
  year: "2014",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 2,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "tambarash",
  category: "digital-art",
  title: "Tambarash",
  year: "2021",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "euu-14-esperienza-ultra-umana",
  category: "digital-art",
  title: "EUU 14 Esperienza Ultra Umana",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "pomeriggio-da-sola",
  category: "digital-art",
  title: "Pomeriggio da sola",
  year: "2021",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "lincubo-dei-condizionamenti",
  category: "digital-art",
  title: "L'incubo dei condizionamenti",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "near-death-experience",
  category: "digital-art",
  title: "Near Death Experience",
  year: "2013",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "il-sottile-strato-che-ci-separa-dal-tutto",
  category: "digital-art",
  title: "Il sottile strato che ci separa dal tutto",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "kontinuum",
  category: "digital-art",
  title: "Kontinuum",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 3,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "lunità-del-tutto",
  category: "digital-art",
  title: "L'unità del tutto",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "endless-tears",
  category: "digital-art",
  title: "Endless tears",
  year: "2014",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "cat-dream",
  category: "digital-art",
  title: "Cat dream",
  year: "2013",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "il-segreto-svelato",
  category: "digital-art",
  title: "Il segreto svelato",
  year: "2016",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "awareness-in-winter",
  category: "digital-art",
  title: "Awareness in winter",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "flash-in-the-evening",
  category: "digital-art",
  title: "Flash in the evening",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "fuori-dagli-schemi",
  category: "digital-art",
  title: "Fuori dagli schemi",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 1,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "evening-abstract",
  category: "digital-art",
  title: "Evening abstract",
  year: "2015",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 0,
  roomViews: 2,
  format: "webp",
  published: true,
}),
createArtwork({
  slug: "battito-primordiale",
  category: "digital-art",
  title: "Battito primordiale",
  year: "2014",
  dimensions: " x  cm",
  technique: "Elaborazione Digitale – Formato variabile",
  price: "€ Prezzo su richiesta",
  details: 7,
  roomViews: 2,
  format: "webp",
  published: true,
  }),
];

/* ═══════════════════════════════════════════════════════════════
 *  T-SHIRT
 * ═══════════════════════════════════════════════════════════════ */
const tShirt: ArtworkFullData[] = [
  createArtwork({ slug: "nebula-wear",     category: "t-shirt", title: "Nebula Wear",     year: "2024", dimensions: "Varie taglie", technique: "Serigrafia" }),
  createArtwork({ slug: "cosmic-print",    category: "t-shirt", title: "Cosmic Print",    year: "2024", dimensions: "Varie taglie", technique: "Stampa digitale" }),
  createArtwork({ slug: "urban-galaxy",    category: "t-shirt", title: "Urban Galaxy",    year: "2024", dimensions: "Varie taglie", technique: "Serigrafia" }),
  createArtwork({ slug: "abstract-flow",   category: "t-shirt", title: "Abstract Flow",   year: "2024", dimensions: "Varie taglie", technique: "Stampa digitale" }),
  createArtwork({ slug: "stellar-edition", category: "t-shirt", title: "Stellar Edition", year: "2023", dimensions: "Varie taglie", technique: "Serigrafia" }),
  createArtwork({ slug: "dark-matter",     category: "t-shirt", title: "Dark Matter",     year: "2023", dimensions: "Varie taglie", technique: "Stampa digitale" }),
];

/* ═══════════════════════════════════════════════════════════════ */

const data: DisciplineData = {
  painting,
  photography,
  "digital-art": digitalArt,
  "t-shirt": tShirt,
};

export function getArtworksByDiscipline(discipline: string): ArtworkFullData[] {
  return data[discipline] || [];
}

export function getArtwork(discipline: string, artworkId: string): ArtworkFullData | undefined {
  return data[discipline]?.find((a) => a.id === artworkId);
}
